# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/sony/extra/stamina/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/sony/extra/stamina

PRODUCT_COPY_FILES += \
    vendor/sony/extra/stamina/proprietary/system_ext/etc/permissions/com.sonymobile.superstamina.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/com.sonymobile.superstamina.xml \
    vendor/sony/extra/stamina/proprietary/vendor/etc/init/vendor.somc.hardware.superstamina@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.somc.hardware.superstamina@1.0-service.rc

PRODUCT_PACKAGES += \
    vendor.somc.hardware.superstamina@1.0 \
    StaminaLevel \
    SuperStamina \
    com.sonymobile.superstamina_impl \
    vendor.somc.hardware.superstamina@1.0-service
