# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/sony/extra/audio-legacy/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),audio-legacy)

endif
