# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/sony/extra/audio-legacy/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/sony/extra/audio-legacy

PRODUCT_COPY_FILES += \
    vendor/sony/extra/audio-legacy/proprietary/vendor/etc/init/vendor.dolby.hardware.dms@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.dolby.hardware.dms@1.0-service.rc \
    vendor/sony/extra/audio-legacy/proprietary/vendor/etc/media_codecs_dolby_audio.xml:$(TARGET_COPY_OUT_VENDOR)/etc/media_codecs_dolby_audio.xml

PRODUCT_PACKAGES += \
    libdapparamstorage \
    libstagefrightdolby \
    libswdap \
    vendor.dolby.hardware.dms@1.0 \
    libstagefright_soft_ac4dec \
    libstagefright_soft_ddpdec \
    libdlbdsservice \
    vendor.dolby.hardware.dms@1.0-impl \
    DaxUI \
    daxService \
    dolby_dax \
    vendor.dolby.hardware.dms@1.0-service
