# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/sony/pdx206-camera/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/sony/extra/camera

PRODUCT_PACKAGES += \
    CameraAddonPermission \
    CameraCommonPermission \
    CameraCommon \
    CameraPanorama-release \
    com.sonymobile.addoncamera.portraitselfie
